// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwJhR6jUmxXPsRjZgCK1hvAwOzhGNcSb8',
    appId: '1:997923251071:android:e83c51adbcd0e320edb04a',
    messagingSenderId: '997923251071',
    projectId: 'jito-visuals',
    storageBucket: 'jito-visuals.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhZfRGcfLc5u1LJbS6f9amtxvLZOzsuXA',
    appId: '1:997923251071:ios:65686998e03e2e29edb04a',
    messagingSenderId: '997923251071',
    projectId: 'jito-visuals',
    storageBucket: 'jito-visuals.firebasestorage.app',
    androidClientId: '997923251071-6q1pd77mo8eistpsk7gv4dg6p4t5pa4p.apps.googleusercontent.com',
    iosClientId: '997923251071-7skgcskaacvmv318e3ognoa5pt5b69h5.apps.googleusercontent.com',
    iosBundleId: 'com.example.jitoVisuals',
  );
}
